# Generated by Django 4.0.3 on 2022-05-15 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bo_bot_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeMessage', models.CharField(max_length=70, verbose_name='Tipo de mensaje:')),
                ('message', models.TextField(verbose_name='Mensaje:')),
                ('status', models.BooleanField(default=True, verbose_name='Estado:')),
            ],
            options={
                'db_table': 'bo_bot_message',
            },
        ),
        migrations.CreateModel(
            name='bo_bot_tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackingPath', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('lastMessage', models.TextField(blank=True, null=True)),
                ('phoneMessageFrom', models.CharField(blank=True, max_length=30, null=True)),
                ('AccountSid', models.CharField(blank=True, max_length=100, null=True)),
                ('sessionAccount', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bo_bot_tracking',
            },
        ),
    ]
