# Generated by Django 4.0.3 on 2022-04-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fi_file_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('linkFather', models.IntegerField()),
                ('isactive', models.IntegerField()),
            ],
        ),
    ]
