# Generated by Django 4.0.3 on 2022-04-30 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fi_file_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('isActive', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Fi_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileTypeName', models.CharField(help_text='Prueba texto', max_length=250, verbose_name='Nombre de Documento:')),
                ('fileDescription', models.TextField(verbose_name='Descripción de archivo:')),
                ('files', models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='Archivo:')),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('fileType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.fi_file_type', verbose_name='Grupo:')),
            ],
        ),
    ]
