# Generated by Django 4.0.3 on 2022-04-21 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fi_file_type',
            old_name='isactive',
            new_name='isActive',
        ),
    ]
