# Generated by Django 4.0.3 on 2022-04-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_rename_isactive_fi_file_type_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fi_file_type',
            old_name='linkFather',
            new_name='parentID',
        ),
    ]
