# Generated by Django 4.0.3 on 2022-04-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_fi_file_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='fi_file',
            name='fileName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
