# Generated by Django 4.0.3 on 2022-04-21 07:30

from django.db import migrations, models
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_rename_linkfather_fi_file_type_parentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fi_file_type',
            name='name',
            field=models.TextField(max_length=250),
        ),
        UnaccentExtension(),
    ]
