# Generated by Django 4.0.3 on 2022-04-30 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_fi_file_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fi_file',
            name='fileName',
        ),
    ]
