# Generated by Django 4.0.3 on 2022-05-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_remove_fi_file_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fi_file',
            name='fileDescription',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de archivo:'),
        ),
    ]
