# Generated by Django 4.0.3 on 2022-04-21 07:51

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_fi_file_type_name'),
    ]

    operations = [
        UnaccentExtension()
    ]
