# Generated by Django 4.0.3 on 2022-05-12 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_fi_file_filedescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fi_file',
            name='fileType',
            field=models.ForeignKey(help_text='Seleccione...', on_delete=django.db.models.deletion.RESTRICT, to='files.fi_file_type', verbose_name='Grupo:'),
        ),
    ]
