# Generated by Django 4.0.3 on 2022-05-12 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_fi_file_filetype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fi_file_type',
            unique_together=set(),
        ),
    ]
