# Generated by Django 4.0.3 on 2022-04-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20220421_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fi_file_type',
            name='isActive',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fi_file_type',
            name='parentID',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
