# Generated by Django 4.0.3 on 2022-05-13 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_fi_file_type_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fi_file',
            name='fileType',
            field=models.ForeignKey(help_text='Seleccione...', limit_choices_to={'isActive': 1}, on_delete=django.db.models.deletion.RESTRICT, to='files.fi_file_type', verbose_name='Grupo:'),
        ),
    ]
