# Generated by Django 4.0.3 on 2022-04-24 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_fi_file_type_isactive_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fi_file_type',
            unique_together={('name',)},
        ),
    ]
